spring.datasource.url=jdbc:postgresql://localhost:5432/geotecnologia
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

api.security.token.secret=${JWT_SECRET:my-secret-key}
security.jwt.expiracao=30

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true